#!/usr/bin/env bash

export ydb_gbldir=/opt/yottadb/yottadb.gld
export ydb_dir=/opt/yottadb
export ydb_routines="/opt/glsdb/m /usr/local/lib/yottadb/r134/libyottadbutil.so"
export ydb_dist=/usr/local/lib/yottadb/r134

$ydb_dist/mumps -dir


